service: serverless-pdf-generator

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node24
    external:
      - '@sparticuz/chromium'

custom:
  stage: ${opt:stage, 'stage'}

  s3:
    responseRegion: 'eu-west-1'
    responseBucket: 'pdf-generator-serverless-responses-test'

  cors:
    origin: '*'
    headers:
      - Accept-Encoding
      - Content-Type
      - Content-Length
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Headers
      - Access-Control-Allow-Methods
    allowCredentials: false

  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs24.x
  region: eu-west-1
  logRetentionInDays: 90
  deploymentBucket: pdf-generator-serverless-deploy-test

  environment:
    NODE_ENV: ${self:custom.stage}
    S3_LARGE_HTTP_RESPONSE_REGION: ${self:custom.s3.responseRegion}
    S3_LARGE_HTTP_RESPONSE_BUCKET: ${self:custom.s3.responseBucket}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: arn:aws:s3:::${self:custom.s3.responseBucket}/*

  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

layers:
  HeadlessChromium:
    name: serverless-headless-chromium-${self:custom.stage}-v143
    description: Layer for puppeteer to launch headless Chromium v143
    compatibleRuntimes:
      - nodejs24.x
    package:
      artifact: layers/chromium-v143.0.4.zip

functions:
  print:
    handler: print/print.handler
    description: Generates a PDF from HTML (using Chromium v143)
    memorySize: 2048
    timeout: 29
    layers:
      - { Ref: HeadlessChromiumLambdaLayer }
    events:
      - http:
          path: /print
          method: POST
          cors: ${self:custom.cors}

  serviceRead:
    handler: service/version.handler
    description: Reads service metadata
    events:
      - http:
          method: GET
          path: service/version
          cors: ${self:custom.cors}

resources:
  Description: API for generating PDF from HTML

plugins:
  - serverless-apigw-binary